### PR TITLE
Get ready for v0.11 and v1.0

### LINKED ISSUE #1: filter-stdout does not working with embulk 0.9.20
I would like to use filter-stdout plugin with recent embulk.
```
2020-02-14 16:01:42.971 +0000: Embulk v0.9.20
2020-02-14 16:01:43.648 +0000 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2020-02-14 16:01:46.266 +0000 [INFO] (main): Gem's home and path are set by default: "/Users/y-ken/.embulk/lib/gems"
2020-02-14 16:01:48.649 +0000 [INFO] (main): Started Embulk v0.9.20
2020-02-14 16:01:48.738 +0000 [INFO] (0001:transaction): Loaded plugin embulk-input-http (0.23.0)
2020-02-14 16:01:48.859 +0000 [INFO] (0001:transaction): Loaded plugin embulk-filter-ruby_proc (0.8.1)
2020-02-14 16:01:48.925 +0000 [INFO] (0001:transaction): Loaded plugin embulk-filter-split_column (0.1.3)
2020-02-14 16:01:48.972 +0000 [INFO] (0001:transaction): Loaded plugin embulk-filter-stdout (0.1.0)
2020-02-14 16:01:49.094 +0000 [INFO] (0001:transaction): Loaded plugin embulk-filter-row (0.5.1)
org.embulk.exec.PartialExecutionException: java.lang.NoClassDefFoundError: org/embulk/filter/stdout/StdoutFilterPlugin$PluginTask
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(Exec.java:22)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:205)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:433)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
	at org.embulk.cli.Main.main(Main.java:64)
	Suppressed: java.lang.NullPointerException
		at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:463)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:397)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:394)
		at org.embulk.spi.Exec.doWith(Exec.java:22)
		at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:394)
		at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:208)
		... 5 more
Caused by: java.lang.NoClassDefFoundError: org/embulk/filter/stdout/StdoutFilterPlugin$PluginTask
	at org.embulk.filter.stdout.StdoutFilterPlugin.transaction(org/embulk/filter/stdout/StdoutFilterPlugin.java:34)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:76)
	at org.embulk.spi.util.Filters$RecursiveControl$1.run(org/embulk/spi/util/Filters.java:80)
	at org.embulk.filter.split_column.SplitColumnFilterPlugin.transaction(org/embulk/filter/split_column/SplitColumnFilterPlugin.java:79)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:76)
	at org.embulk.spi.util.Filters$RecursiveControl$1.run(org/embulk/spi/util/Filters.java:80)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:468)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:326)
	at RUBY.block in transaction(uri:classloader:/gems/embulk-0.9.20-java/lib/embulk/filter_plugin.rb:54)
	at RUBY.transaction(/Users/y-ken/.embulk/lib/gems/gems/embulk-filter-ruby_proc-0.8.1/lib/embulk/filter/ruby_proc.rb:113)
	at RUBY.transaction(uri:classloader:/gems/embulk-0.9.20-java/lib/embulk/filter_plugin.rb:51)
	at Embulk$$FilterPlugin$$JavaAdapter_414874500.transaction(Embulk$$FilterPlugin$$JavaAdapter_414874500.gen:13)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:76)
	at org.embulk.spi.util.Filters.transaction(org/embulk/spi/util/Filters.java:42)
	at org.embulk.exec.BulkLoader$4.run(org/embulk/exec/BulkLoader.java:511)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(org/embulk/spi/FileInputRunner.java:112)
	at org.embulk.standards.JsonParserPlugin.transaction(org/embulk/standards/JsonParserPlugin.java:102)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(org/embulk/spi/FileInputRunner.java:107)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(org/embulk/spi/util/Decoders.java:68)
	at org.embulk.spi.util.Decoders.transaction(org/embulk/spi/util/Decoders.java:29)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(org/embulk/spi/FileInputRunner.java:105)
	at org.embulk.input.http.HttpFileInputPlugin.resume(org/embulk/input/http/HttpFileInputPlugin.java:86)
	at org.embulk.input.http.HttpFileInputPlugin.transaction(org/embulk/input/http/HttpFileInputPlugin.java:81)
	at org.embulk.spi.FileInputRunner.transaction(org/embulk/spi/FileInputRunner.java:62)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:507)
	at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:22)
	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:205)
	at org.embulk.EmbulkRunner.runInternal(org/embulk/EmbulkRunner.java:292)
	at org.embulk.EmbulkRunner.run(org/embulk/EmbulkRunner.java:156)
	at org.embulk.cli.EmbulkRun.runSubcommand(org/embulk/cli/EmbulkRun.java:433)
	at org.embulk.cli.EmbulkRun.run(org/embulk/cli/EmbulkRun.java:90)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:64)

Error: java.lang.NoClassDefFoundError: org/embulk/filter/stdout/StdoutFilterPlugin$PluginTask
2020-02-15 01:01:49 +0900 [ERROR] (0019@[0:default]+***********): Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
	at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:315)
	at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:705)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:257)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:687)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
This PR catchup [Get ready for v0.11 and v1.0!](https://dev.embulk.org/topics/get-ready-for-v0.11-and-v1.0.html)

This PR also fix https://github.com/sonots/embulk-filter-stdout/issues/1#issuecomment-619551032

@dmikurube Could you take a look when you get a chance?

### CODE REVIEW

**Review by dmikurube — APPROVED** [review]
LGTM, but don't we configure publishing?

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for your review. I add the `publishing` configuration.

**Comment by hiroyuki-sato** [comment]
@sonots Could you take a look when you get a chance?
